export enum RoleEnum {
  SOFTWARE_ENGINEER = "SOFTWARE_ENGINEER",
  PROJECT_MANAGER = "PROJECT_MANAGER",
  SOLUTION_ARCHITECT = "SOLUTION_ARCHITECT",
  SOLUTION_ENGINEER = "SOLUTION_ENGINEER",
  LEAD_ENGINEER = "LEAD_ENGINEER",
  DELIVERY_MANAGER = "DELIVERY_MANAGER",
}
